/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml.impl;

import java.util.List;
import java.util.Map;

import org.eclipse.emf.ecore.EClass;
import org.xtext.example.mydsl.mml.AlgorithmVisitor;
import org.xtext.example.mydsl.mml.GTB;
import org.xtext.example.mydsl.mml.MmlPackage;

/**
 * <!-- begin-user-doc --> An implementation of the model object
 * '<em><b>GTB</b></em>'. <!-- end-user-doc -->
 *
 * @generated
 */
public class GTBImpl extends MLAlgorithmImpl implements GTB {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected GTBImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MmlPackage.Literals.GTB;
	}
	
	@Override
	public Map<String,List<String>> accept(AlgorithmVisitor<Map<String,List<String>>> v) {
		return v.visit(this);
	}

} // GTBImpl
