/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml.impl;

import java.util.List;
import java.util.Map;

import org.eclipse.emf.ecore.EClass;
import org.xtext.example.mydsl.mml.AlgorithmVisitor;
import org.xtext.example.mydsl.mml.MmlPackage;
import org.xtext.example.mydsl.mml.RandomForest;

/**
 * <!-- begin-user-doc --> An implementation of the model object '<em><b>Random
 * Forest</b></em>'. <!-- end-user-doc -->
 *
 * @generated
 */
public class RandomForestImpl extends MLAlgorithmImpl implements RandomForest {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected RandomForestImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MmlPackage.Literals.RANDOM_FOREST;
	}

	@Override
	public Map<String,List<String>> accept(AlgorithmVisitor<Map<String,List<String>>> v) {
		return v.visit(this);
	}

} // RandomForestImpl
