/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.tests.bobo_abdellah_sabrina_charaf

import com.google.common.io.Files
import com.google.inject.Inject
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.util.List
import java.util.Map
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.mydsl.mml.DataInput
import org.xtext.example.mydsl.mml.FrameworkLang
import org.xtext.example.mydsl.mml.MLAlgorithm
import org.xtext.example.mydsl.mml.MLChoiceAlgorithm
import org.xtext.example.mydsl.mml.MMLModel
import org.xtext.example.mydsl.mml.StratificationMethod
import org.xtext.example.mydsl.mml.Validation
import org.xtext.example.mydsl.mml.ValidationMetric
import org.xtext.example.mydsl.mml.impl.AlgorithmVisitorImpl
import org.xtext.example.mydsl.tests.MmlInjectorProvider

@ExtendWith(InjectionExtension)
@InjectWith(MmlInjectorProvider)
class MmlParsingTest {
	@Inject
	ParseHelper<MMLModel> parseHelper

	@Test
	def void loadModel() {
		val MMLModel result = parseHelper.parse('''
			datainput "boston.csv"
				mlframework scikit-learn
				algorithm DT
				TrainingTest { 
					percentageTraining 70
				}
				mean_absolute_error
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		Assertions.assertEquals("boston.csv", result.input.filelocation)
	}

	@Test
	def void compileDataInput() {
		val MMLModel result = parseHelper.parse('''
			datainput "boston.csv" separator ;
				mlframework scikit-learn
				algorithm DT
				TrainingTest { 
					percentageTraining 70
				}
				mean_absolute_error
		''')
		val DataInput dataInput = result.input;
		val String fileLocation = dataInput.filelocation;
		
		//Algorithm
		val MLChoiceAlgorithm mlChoiceAlgorithm = result.algorithm;
		val FrameworkLang frameworklang = mlChoiceAlgorithm.framework;
		val MLAlgorithm mlAlgorithm = mlChoiceAlgorithm.algorithm;
		val Map<String,List<String>> map = mlAlgorithm.accept(new AlgorithmVisitorImpl("DT"));
		
		//TrainningTest
		val Validation validation = result.validation;
		val StratificationMethod stratification = validation.stratification;
		//Metric
		val List<ValidationMetric> metrics = validation.metric;
		
		//TrainningPercentage
		val double percentageTraining = stratification.number as double / 100.0;
		val double percentageTest = 1.0 - percentageTraining;
		
		val String trainning = "train_test_split";
		
		// start of Python generation
		var String pythonImport = "import pandas as pd\n";
		for(String input:map.get("inputs")){
			pythonImport += input+"\n";
		}
		
		for(ValidationMetric validationMetric: metrics){
			pythonImport += "from sklearn.metrics import "+validationMetric.literal.toString()+"\n";
		}
		pythonImport += "from sklearn.model_selection import "+trainning+"\n";
		
		
		/*
		if (parsingInstruction != null) {
			System.err.println("parsing instruction..." + parsingInstruction);
			csv_separator = parsingInstruction.getSep().toString();
		}
		*/
		val String	csvReading = "\nmml_data = pd.read_csv(\""+ fileLocation + "\")";
		var String	pandasCode = pythonImport + csvReading;
		val String column = "\ncolumn = mml_data.columns[-1]";
		pandasCode += "\n"+column+" \nX = mml_data.drop(columns=[column]) ";
		pandasCode += "\ny = mml_data[column] ";
		pandasCode += "\ntest_size = "+ percentageTest ;
		pandasCode += "\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size) ";
		for(String body:map.get("body")){
			pandasCode += "\n"+body;
		}
		
		for(ValidationMetric validationMetric: metrics){
			pandasCode += "\naccuracy = "+validationMetric.literal.toString()+"(y_test, y_pred)";
			pandasCode += "\nprint('"+validationMetric.literal.toString()+":', accuracy)";
		}
		
		
		Files.write(pandasCode.getBytes(), new File("mml.py"));
		// end of Python generation
		/*
		 * Calling generated Python script (basic solution through systems call)
		 * we assume that "python" is in the path
		 * 
		 * virtualenv -p python3 venv
		 * 
		 * venv/bin/pip install -r requirements.txt
		 */
		
		val Process	p = Runtime.getRuntime().exec("python mml.py");
		val BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
		var String line;
		
		while (( line = in.readLine()) !== null) {
			System.out.println(line);
		}
	/*
		private String mkValueInSingleQuote
		(String val){
			return "'" +
		val + "'";
		}
		val String DEFAULT_COLUMN_SEPARATOR = ","; // by default
		val String csv_separator = DEFAULT_COLUMN_SEPARATOR;
		val String SCIKIT = "scikit-learn";
		val String test = "";
		val String pythonAlgorithm = "DecisionTree";
		
		*/
	}
}